language: python
python:
  - 3.6
services:
  - docker
install:
  - docker build -t max-text-summarizer .
  - docker run -it -d --rm -p 5000:5000 max-text-summarizer
  - pip install -r requirements-test.txt
script:
  - flake8 . --max-line-length=127 --exclude=./core/getpoint
  - sleep 30
  # "python -m" will add current working directory to sys.path.
  # See https://docs.pytest.org/en/latest/usage.html#calling-pytest-through-python-m-pytest
  - python -m pytest tests/test.py
